export const data = {
  proejcts: {
    old: [
      {
        name: 'Farmasi',
        number: 1,
        tags: ['HTML', 'CSS', 'JavaScript', 'Bootstrap'],
        img: 'imagini/farmasi.png',
        link: 'https://site.peter-szilaghi.com/farmasi/',
      },
      {
        name: 'Duolife',
        number: 2,
        tags: ['HTML', 'CSS', 'Bootstrap'],
        img: 'imagini/duolife.png',
        link: 'https://site.peter-szilaghi.com/duolife/',
      },
      {
        name: 'Landing Page',
        number: 3,
        tags: ['HTML', 'CSS', 'Bootstrap'],
        img: 'imagini/serviciu-1.png',
        link: 'https://site.peter-szilaghi.com/produse-sau-servicii/',
      },
      {
        name: 'Mini Game',
        number: 4,
        tags: ['HTML', 'CSS', 'JavaScript', 'Bootstrap'],
        img: 'imagini/first-mini-game.png',
        link: 'https://apps.peter-szilaghi.com/rls-game/index.html',
      },
      {
        name: 'Site v1',
        number: 5,
        tags: ['HTML', 'CSS', 'JavaScript', 'Bootstrap'],
        img: 'imagini/old-version-1.png',
        link: 'https://site.peter-szilaghi.com/site-v1/',
      },
      {
        name: 'Calc Dobanda Compusa',
        number: 6,
        tags: ['HTML', 'CSS', 'JavaScript'],
        img: 'imagini/calc-dob-comp.png',
        link: 'https://apps.peter-szilaghi.com/calculator-dobanda-compusa/',
      },
      {
        name: 'Calc Salarii',
        number: 7,
        tags: ['HTML', 'CSS', 'JavaScript'],
        img: 'imagini/calculator-salarii.png',
        link: 'https://apps.peter-szilaghi.com/calculator-salar/',
      },
      {
        name: 'To Do List',
        number: 8,
        tags: ['HTML', 'CSS', 'JavaScript'],
        img: 'imagini/to-do-list.png',
        link: 'https://apps.peter-szilaghi.com/to-do-list/',
      },
    ],
    course: [
      {
        name: 'Tindog',
        number: 1,
        tags: ['HTML', 'CSS', 'Bootstrap'],
        img: 'imagini/tindog.png',
        link: 'https://peter-szilaghi.github.io/tindog/',
      },
      {
        name: 'Dice game',
        number: 2,
        tags: ['HTML', 'CSS', 'JavaScript'],
        img: 'imagini/dice-game.png',
        link: 'https://github.com/Peter-Szilaghi/dice-game',
      },
      {
        name: 'Simon Game',
        number: 3,
        tags: ['HTML', 'CSS', 'JavaScript'],
        img: 'imagini/simon-game.png',
        link: 'https://peter-szilaghi.github.io/simon-game/',
      },
      {
        name: 'Drum Kit',
        number: 4,
        tags: ['HTML', 'CSS', 'JavaScript'],
        img: 'imagini/drumkit.png',
        link: 'https://peter-szilaghi.github.io/drum-kit/',
      },
      {
        name: 'Omnifood',
        number: 5,
        tags: ['HTML', 'CSS'],
        img: 'imagini/omnifood.png',
        link: 'https://peter-szilaghi.github.io/omnifood/',
      },
      {
        name: 'Natours',
        number: 6,
        tags: ['HTML', 'CSS', 'SASS'],
        img: 'imagini/natours.png',
        link: 'https://peter-szilaghi.github.io/Natours/',
      },
      {
        name: 'Trillo',
        number: 7,
        tags: ['HTML', 'CSS', 'SASS'],
        img: 'imagini/trillo.png',
        link: 'https://peter-szilaghi.github.io/Trillo/',
      },
      {
        name: 'Nexter',
        number: 7,
        tags: ['HTML', 'CSS', 'SASS'],
        img: 'imagini/nexter.png',
        link: 'https://peter-szilaghi.github.io/Nexter/',
      },
      {
        name: 'Guess Number',
        number: 8,
        tags: ['HTML', 'CSS', 'JavaScript'],
        img: 'imagini/guess-number.png',
        link: 'https://peter-szilaghi.github.io/Guess-My-Number/',
      },
      {
        name: 'Pig Game',
        number: 9,
        tags: ['HTML', 'CSS', 'JavaScript'],
        img: 'imagini/pig-game.png',
        link: 'https://peter-szilaghi.github.io/Pig-Game/',
      },
      {
        name: 'Bank App',
        number: 10,
        tags: ['HTML', 'CSS', 'JavaScript'],
        img: 'imagini/bankist.png',
        link: 'https://peter-szilaghi.github.io/Bankist/',
      },
      {
        name: 'Mapty App',
        number: 11,
        tags: ['HTML', 'CSS', 'JavaScript'],
        img: 'imagini/mapty.png',
        link: 'https://peter-szilaghi.github.io/Mapty/',
      },
      {
        name: 'Forkify App',
        number: 12,
        tags: ['HTML', 'CSS', 'JavaScript'],
        img: 'imagini/forkify.png',
        link: 'https://peter-szilaghi.github.io/forkify-app/',
      },
    ],
    personal: [
      {
        name: 'Acesta pagina',
        number: 1,
        tags: ['HTML', 'CSS', 'SASS', 'JavaScript'],
        img: 'imagini/site-v4.2.png',
        link: '#',
      },
      {
        name: 'Note App',
        number: 2,
        tags: ['HTML', 'CSS', 'JavaScript', 'NodeJs', 'MongoDB'],
        img: 'imagini/note-app.png',
        link: 'https://note.peter-szilaghi.com/',
      },
    ],
  },
};
